"""
Contract Verification Engine for OntoPrune.

Inspects code generated by LLMs to detect hallucinated or unauthorized
API calls by comparing against the grounded ontological contract.
Supports Python, Dart/Flutter, Java, and TypeScript.
"""

from __future__ import annotations

import ast
import re
from typing import Any

from ontoprune.parser import BUILTIN_FUNCTIONS

DART_BUILTINS: set[str] = {
    "print",
    "setState",
    "notifyListeners",
    "dispose",
    "initState",
    "build",
    "toString",
    "hashCode",
    "noSuchMethod",
    "then",
    "catchError",
    "whenComplete",
    "map",
    "where",
    "toList",
    "toSet",
    "forEach",
    "reduce",
    "fold",
    "cast",
    "add",
    "addAll",
    "remove",
    "clear",
    "contains",
    "indexOf",
    "sublist",
    "Future",
    "Stream",
    "Iterable",
    "List",
    "Map",
    "Set",
    "String",
    "int",
    "double",
    "bool",
    "num",
    "DateTime",
    "Duration",
    "Text",
    "Container",
    "Column",
    "Row",
    "Center",
    "Padding",
    "SizedBox",
    "Expanded",
    "Scaffold",
    "AppBar",
    "Icon",
    "Icons",
    "EdgeInsets",
    "Color",
    "Colors",
    "Key",
    "Widget",
    "StatelessWidget",
    "StatefulWidget",
    "State",
}

JAVA_BUILTINS: set[str] = {
    "equals",
    "hashCode",
    "toString",
    "getClass",
    "notify",
    "notifyAll",
    "wait",
    "println",
    "print",
    "printf",
    "format",
    "get",
    "set",
    "add",
    "addAll",
    "remove",
    "clear",
    "contains",
    "containsKey",
    "containsValue",
    "isEmpty",
    "size",
    "length",
    "stream",
    "map",
    "filter",
    "collect",
    "forEach",
    "findFirst",
    "findAny",
    "orElse",
    "orElseGet",
    "orElseThrow",
    "isPresent",
    "ifPresent",
    "builder",
    "build",
    "valueOf",
    "parse",
    "compareTo",
    "clone",
    "of",
    "toList",
    "toSet",
}

TS_BUILTINS: set[str] = {
    "console",
    "log",
    "error",
    "warn",
    "info",
    "map",
    "filter",
    "reduce",
    "forEach",
    "find",
    "findIndex",
    "some",
    "every",
    "includes",
    "indexOf",
    "push",
    "pop",
    "shift",
    "unshift",
    "slice",
    "splice",
    "concat",
    "join",
    "reverse",
    "sort",
    "flat",
    "flatMap",
    "length",
    "toString",
    "trim",
    "toLowerCase",
    "toUpperCase",
    "replace",
    "replaceAll",
    "split",
    "substring",
    "startsWith",
    "endsWith",
    "stringify",
    "parse",
    "then",
    "catch",
    "finally",
    "all",
    "race",
    "allSettled",
    "resolve",
    "reject",
    "keys",
    "values",
    "entries",
    "assign",
    "hasOwn",
    "setTimeout",
    "clearTimeout",
    "setInterval",
    "clearInterval",
    "fetch",
    "useState",
    "useEffect",
    "useCallback",
    "useMemo",
    "useRef",
    "useContext",
    "useReducer",
    "Number",
    "String",
    "Boolean",
    "Array",
    "Object",
    "Promise",
    "Date",
    "Math",
    "JSON",
    "Error",
}


def extract_code_blocks(text: str) -> str:
    """Extract code from markdown code fences or return raw text if none."""
    pattern = r"```[a-zA-Z0-9_-]*\s*\n(.*?)\n```"
    matches = re.findall(pattern, text, re.DOTALL)
    if matches:
        return "\n\n".join(matches)
    return text


class PythonCallExtractor(ast.NodeVisitor):
    """AST visitor to extract all invoked function and method names in Python."""

    def __init__(self) -> None:
        self.calls: set[str] = set()
        self.locally_defined: set[str] = set()

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self.locally_defined.add(node.name)
        self.generic_visit(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self.locally_defined.add(node.name)
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Name):
            self.calls.add(node.func.id)
        elif isinstance(node.func, ast.Attribute):
            self.calls.add(node.func.attr)
        self.generic_visit(node)


def extract_dart_calls(code_text: str) -> tuple[set[str], set[str]]:
    """Extract method invocations and local declarations from Dart code."""
    try:
        from ontoprune.treesitter_parser import DartParser

        parser = DartParser()
        tree = parser.parser.parse(code_text.encode("utf-8"))

        invocations: set[str] = set()
        defs: set[str] = set()

        def find_symbols(node: Any) -> None:
            if node.type == "function_signature":
                for c in node.children:
                    if c.type == "identifier":
                        defs.add(c.text.decode("utf-8"))
            for i, child in enumerate(node.children):
                if child.type == "selector":
                    for sc in child.children:
                        if sc.type == "unconditional_assignable_selector":
                            if i + 1 < len(node.children):
                                next_sib = node.children[i + 1]
                                if next_sib.type == "selector" and any(
                                    c.type == "argument_part" for c in next_sib.children
                                ):
                                    for id_c in sc.children:
                                        if id_c.type == "identifier":
                                            invocations.add(id_c.text.decode("utf-8"))
                elif child.type == "identifier":
                    if i + 1 < len(node.children):
                        next_sib = node.children[i + 1]
                        if next_sib.type == "selector" and any(
                            c.type == "argument_part" for c in next_sib.children
                        ):
                            invocations.add(child.text.decode("utf-8"))
                find_symbols(child)

        find_symbols(tree.root_node)
        return invocations, defs
    except Exception:
        # Fallback to regex
        matches = set(re.findall(r"\b([a-zA-Z_]\w*)\s*\(", code_text))
        return matches, set()


def extract_java_calls(code_text: str) -> tuple[set[str], set[str]]:
    """Extract method invocations and local declarations from Java code."""
    try:
        from ontoprune.treesitter_parser import JavaParser

        parser = JavaParser()
        tree = parser.parser.parse(code_text.encode("utf-8"))

        invocations: set[str] = set()
        defs: set[str] = set()

        def walk(n: Any) -> None:
            if n.type == "method_declaration":
                for c in n.children:
                    if c.type == "identifier":
                        defs.add(c.text.decode("utf-8"))
            elif n.type == "method_invocation":
                m_name = None
                for c in n.children:
                    if c.type == "identifier":
                        m_name = c.text.decode("utf-8")
                if m_name:
                    invocations.add(m_name)
            for child in n.children:
                walk(child)

        walk(tree.root_node)
        return invocations, defs
    except Exception:
        matches = set(re.findall(r"\b([a-zA-Z_]\w*)\s*\(", code_text))
        return matches, set()


def extract_ts_calls(code_text: str) -> tuple[set[str], set[str]]:
    """Extract method invocations and local declarations from TypeScript/JavaScript code."""
    try:
        from ontoprune.treesitter_parser import TypeScriptParser

        parser = TypeScriptParser(is_tsx=True)
        tree = parser.parser.parse(code_text.encode("utf-8"))

        invocations: set[str] = set()
        defs: set[str] = set()

        def walk(n: Any) -> None:
            if n.type in ("method_definition", "function_declaration"):
                for c in n.children:
                    if c.type in ("property_identifier", "identifier"):
                        defs.add(c.text.decode("utf-8"))
            elif n.type == "variable_declarator":
                id_node = n.child_by_field_name("name")
                val_node = n.child_by_field_name("value")
                if (
                    id_node
                    and val_node
                    and val_node.type in ("arrow_function", "function_expression")
                ):
                    defs.add(id_node.text.decode("utf-8"))
            elif n.type == "call_expression":
                fn_node = n.child_by_field_name("function")
                if fn_node:
                    if fn_node.type == "member_expression":
                        prop = fn_node.child_by_field_name("property")
                        if prop:
                            invocations.add(prop.text.decode("utf-8"))
                    elif fn_node.type == "identifier":
                        invocations.add(fn_node.text.decode("utf-8"))
            for child in n.children:
                walk(child)

        walk(tree.root_node)
        return invocations, defs
    except Exception:
        matches = set(re.findall(r"\b([a-zA-Z_]\w*)\s*\(", code_text))
        return matches, set()


def extract_authorized_names(contract_text_or_data: Any) -> set[str]:
    """
    Extracts set of allowed function, method, and class names from
    rendered contracts (stubs, turtle, json, or text).
    """
    names: set[str] = set()

    if isinstance(contract_text_or_data, dict):
        if "target" in contract_text_or_data:
            target = contract_text_or_data["target"]
            names.add(target["name"].split(".")[-1])
        for dep in contract_text_or_data.get("allowed_dependencies", []):
            names.add(dep["name"].split(".")[-1])
            if dep.get("class"):
                names.add(dep["class"])
        return names

    text = str(contract_text_or_data)

    # 1. Regex for def <name>( in Python stubs
    stub_defs = re.findall(r"def\s+([a-zA-Z_]\w*)\s*\(", text)
    names.update(stub_defs)

    # 2. Regex for Dart / Java / TS class, interface, and abstract class declarations
    type_defs = re.findall(
        r"(?:export\s+)?(?:abstract\s+class|class|interface)\s+([a-zA-Z_]\w*)", text
    )
    names.update(type_defs)

    # 3. Regex for Dart / Java typed method signatures: RetType methodName(...)
    typed_methods = re.findall(r"(?:void|[a-zA-Z_]\w*(?:<[^>]+>)?)\s+([a-zA-Z_]\w*)\s*\(", text)
    names.update(typed_methods)

    # 4. Regex for TypeScript interface method signatures: methodName(args): RetType;
    ts_methods = re.findall(r"([a-zA-Z_]\w*)\s*\([^)]*\)\s*:\s*[a-zA-Z_]", text)
    names.update(ts_methods)

    # 5. Regex for func_<name> in turtle
    turtle_funcs = re.findall(r"func_(?:[a-zA-Z_]\w*\.)?([a-zA-Z_]\w*)", text)
    names.update(turtle_funcs)

    # 6. Regex for labels rdfs:label "<name>"
    labels = re.findall(r'rdfs:label\s+"([^"]+)"', text)
    for label in labels:
        names.add(label.split(".")[-1])

    # 7. Regex for json/nl quotes
    quotes = re.findall(r"'([a-zA-Z_]\w*)'", text)
    names.update(quotes)

    return names


def check(response: str, against: Any, language: str | None = None) -> list[str]:
    """
    Verifies an LLM response against the contract.
    Returns list of unauthorized / hallucinated API calls.
    """
    code_text = extract_code_blocks(response)
    authorized = extract_authorized_names(against)

    is_dart = language == "dart" or (
        language is None
        and (
            "abstract class" in str(against)
            or "// === OntoPrune Contract: Dart" in str(against)
            or "@override" in code_text
            or "Future<" in code_text
            or "Widget build" in code_text
        )
    )

    is_java = language == "java" or (
        language is None
        and not is_dart
        and (
            "public interface" in str(against)
            or "// === OntoPrune Contract: Java" in str(against)
            or "public class" in code_text
            or "public interface" in code_text
            or "@Autowired" in code_text
            or "@Transactional" in code_text
            or "@Override" in code_text
        )
    )

    is_ts = language in ("ts", "typescript", "tsx", "js", "javascript") or (
        language is None
        and not is_dart
        and not is_java
        and (
            "export interface" in str(against)
            or "// === OntoPrune Contract: TypeScript" in str(against)
            or "export interface" in code_text
            or "export const" in code_text
            or "const " in code_text
            or "async (" in code_text
            or "await " in code_text
            or "Promise<" in code_text
            or "React" in code_text
        )
    )

    if is_dart:
        observed_calls, local_defs = extract_dart_calls(code_text)
        observed_calls = observed_calls - local_defs
        effective_builtins = BUILTIN_FUNCTIONS | DART_BUILTINS
    elif is_java:
        observed_calls, local_defs = extract_java_calls(code_text)
        observed_calls = observed_calls - local_defs
        effective_builtins = BUILTIN_FUNCTIONS | JAVA_BUILTINS
    elif is_ts:
        observed_calls, local_defs = extract_ts_calls(code_text)
        observed_calls = observed_calls - local_defs
        effective_builtins = BUILTIN_FUNCTIONS | TS_BUILTINS
    else:
        extractor = PythonCallExtractor()
        try:
            tree = ast.parse(code_text)
            extractor.visit(tree)
            observed_calls = extractor.calls - extractor.locally_defined
        except SyntaxError:
            matches = set(re.findall(r"\b([a-zA-Z_]\w*)\s*\(", code_text))
            observed_calls = matches
        effective_builtins = BUILTIN_FUNCTIONS

    # Identify calls not in authorized set and not standard builtins
    violations: list[str] = []
    for call_name in sorted(observed_calls):
        if call_name.startswith("__") and call_name.endswith("__"):
            continue
        if call_name not in authorized and call_name not in effective_builtins:
            violations.append(call_name)

    return violations
