"""
Contract Verification Engine for OntoPrune.

Inspects code generated by LLMs to detect hallucinated or unauthorized
API calls by comparing against the grounded ontological contract.
"""

from __future__ import annotations

import ast
import re
from typing import Any

from ontoprune.parser import BUILTIN_FUNCTIONS


def extract_code_blocks(text: str) -> str:
    """Extract code from markdown code fences or return raw text if none."""
    pattern = r"```(?:python)?\s*\n(.*?)\n```"
    matches = re.findall(pattern, text, re.DOTALL)
    if matches:
        return "\n\n".join(matches)
    return text


class CallExtractor(ast.NodeVisitor):
    """AST visitor to extract all invoked function and method names."""

    def __init__(self) -> None:
        self.calls: set[str] = set()
        self.locally_defined: set[str] = set()

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self.locally_defined.add(node.name)
        self.generic_visit(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self.locally_defined.add(node.name)
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Name):
            self.calls.add(node.func.id)
        elif isinstance(node.func, ast.Attribute):
            self.calls.add(node.func.attr)
        self.generic_visit(node)


def extract_authorized_names(contract_text_or_data: Any) -> set[str]:
    """
    Extracts set of allowed function, method, and class names from
    rendered contracts (stubs, turtle, json, or text).
    """
    names: set[str] = set()

    if isinstance(contract_text_or_data, dict):
        # JSON contract
        if "target" in contract_text_or_data:
            target = contract_text_or_data["target"]
            names.add(target["name"].split(".")[-1])
        for dep in contract_text_or_data.get("allowed_dependencies", []):
            names.add(dep["name"].split(".")[-1])
            if dep.get("class"):
                names.add(dep["class"])
        return names

    text = str(contract_text_or_data)

    # 1. Regex for def <name>( in stubs
    stub_defs = re.findall(r"def\s+([a-zA-Z_]\w*)\s*\(", text)
    names.update(stub_defs)

    # 2. Regex for func_<name> in turtle
    turtle_funcs = re.findall(r"func_(?:[a-zA-Z_]\w*\.)?([a-zA-Z_]\w*)", text)
    names.update(turtle_funcs)

    # 3. Regex for labels rdfs:label "<name>"
    labels = re.findall(r'rdfs:label\s+"([^"]+)"', text)
    for label in labels:
        names.add(label.split(".")[-1])

    # 4. Regex for json/nl quotes
    quotes = re.findall(r"'([a-zA-Z_]\w*)'", text)
    names.update(quotes)

    return names


def check(response: str, against: Any) -> list[str]:
    """
    Verifies an LLM response against the contract.
    Returns list of unauthorized / hallucinated API calls.
    """
    code_text = extract_code_blocks(response)
    authorized = extract_authorized_names(against)

    # Add common language constructs
    authorized.update(BUILTIN_FUNCTIONS)

    extractor = CallExtractor()
    try:
        tree = ast.parse(code_text)
        extractor.visit(tree)
        observed_calls = extractor.calls - extractor.locally_defined
    except SyntaxError:
        # Fallback regex extraction if code snippet is incomplete
        matches = re.findall(r"\b([a-zA-Z_]\w*)\s*\(", code_text)
        observed_calls = set(matches)

    # Identify calls not in authorized set and not standard builtins
    violations: list[str] = []
    for call_name in sorted(observed_calls):
        if call_name.startswith("__") and call_name.endswith("__"):
            continue
        if call_name not in authorized and call_name not in BUILTIN_FUNCTIONS:
            violations.append(call_name)

    return violations
